const dataIndex = {
    data: {
        level:0,
        task_index:0,
        activeModuleCode:"",
        activeSubModuleCode:"",
        activeComponentCode:"",
        activeObjectCode:"",
        activeTaskCode:"",
        activeScreenCode:"",
        previousScreenCode:"",
        activeItemData:undefined,
        nav_items:{
            app:{
                isActive:true,
                label:'Modules'
            },
    
        },
        modules: [],
        subModules: [],
        components: [],
        objects: [],
        tasks:[],
        cols_3: ['0','1','2'],
        cols_4: ['0','1','2','3'],
        cols_sys_3: ['0', '1', '2'],
        hasNew:true,
        activeColumn: '',
        itemSearchString:'',
        objectSearchString:'',
        itemFilterAttributes:'{}',
        activeListFilters:[],
        activeDetail : 0,
        handleShowModalReport: true,
        toastrWaiting:false,
        objectLevel:0,
        systemModuleTimer:null,
        moduleTimer:null,
        selectedInstances:{},
        runtimeAttributes:{},
        module_power:{},
        searchModuleValue:[],
        inputSearchModule:'',
        refresh_rate:false,
        lastTask:{},
        current:{},
        checkScreenCP:[],
        activeScreenSub:[],
        activeScreenCom:[],
        activeScreenComPre:[],
        activeFilterAndSearchCom:[],
        multiObject:[],
        checkOneModule:{},
        listTabs:{},
        tabModuleActive:'',
        moduleOffset:0,
        moduleLimit:5,
        moduleList: {},
        taskCP:"",
        titleSkipObject:"",
        activeScreenSkipObject:"",
        checkFilterSkipObject:0,
        topBar:{},
        topBarModule:false,
        item_buttons:[],
        task:"",
        icon_button:"",
        show_button:false,
        appSetting:"",
        ownedDomains:{},
        sortFilter:{},
        stateSortFilter:false,
        backToModule:{},
        taskcallAB:'',
        jsonHolder:{},
        componentABactive:false,
        statusPopup:true,
        timeCheckHeight:0,
        dmobj:{},
        statusdmobj:true,
        heightHomeView:"",
        renderHomeView:false,
        statusHomeView:false,
        dbFilenameArr:[],
        bgcolorHomeview:"",
        shouldCheckVisible: false,
        statusGetDataBackground:false,
        tracking_id_button:'',
        time_tracking_id:{},
        payloadLifetime:{},
        listSreenTheme:{},
        jsonDataParent: {},
    },
  }